
management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true

info:
  application:
    name: cribhub
    description: Shared accommodation management system
    author: maloha
    version: '@project.version@'
spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: create