spring:
  datasource:
    url: jdbc:postgresql://db:5432/cribhub
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

